### ISSUE TITLE
Wrap chatbot CSS to prevent it from leaking to main page styles

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/airindia#39]
Currently, some chatbot CSS styles are global and end up influencing main page styles. Ideally they should be wrapped in chatbot parent selector to ensure that they remain encapsulated. It should be ensure that encapsulating these styles doesn't end up breaking page styles which are currently (incorrectly) influence by it.

**Comment by Akash-AirIndia** [comment]
We are using bootstrap CSS are coming as global. From your end you guys need no avoid the overriding of the generic styles like bootstrap.css.

ai-chatbot.css contains bootstrap CSS and font families.

**Comment by sselvara** [comment]
@Akash-AirIndia  it seems that the global css styles(eg., h3, p) are excluded from stage version of ai-chatbot.css ([stage ai-chatbot.css](https://cbot-scripts-staging.airindia.com/ai-chatbot.css)). However we can still see those in prod version ([prod ai-chatbot.css](https://cbot-scripts.airindia.com/ai-chatbot.css)), which will impact our page's styles.

**Comment by sselvara** [comment]
@Akash-AirIndia, As discussed, we are good with the stage version and assume that it will be deployed in prod as well.
