### ISSUE TITLE
Header anchor tags are missing href attributes(Desktop/Mobile)

### ISSUE THREAD

**Issue by adobenitesh** [hlxsites/airindia#42]
<img width="406" alt="Screenshot 2024-02-01 at 11 44 53 AM" src="https://github.com/hlxsites/airindia/assets/147729087/6377f3cb-11bc-4079-a73d-b15d57a084d6">

**Comment by kalimuthu-a** [comment]
Fixed as part of PR [https://github.com/hlxsites/airindia/pull/71](https://github.com/hlxsites/airindia/pull/71 )
