### ISSUE TITLE
Clicking on Multicity gives a 404 page

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/airindia#62]

**Comment by sselvara** [comment]
@sdmcraft, multicity url is a configuration in the code. We are using the same configuration from the live sire and it is a relative path, it will work as expected once the code is moved to prod(www.airindia.com) domain.

https://www.airindia.com:
<img width="1287" alt="image" src="https://github.com/hlxsites/airindia/assets/25244481/04d8e3a7-7e65-4c7c-99ae-067083a5fe34">

https://ai-eds-test.airindia.com:
<img width="1287" alt="image" src="https://github.com/hlxsites/airindia/assets/25244481/0a54f279-3473-40a0-8561-2709d675601b">

**Comment by sdmcraft** [comment]
@sselvara , can we add a decorator after the booking widget loads to rewrite all hrefs in it to absolute URLs ?

**Comment by sdmcraft** [comment]
@sselvara , by when when can we get this merged?
