### ISSUE TITLE
Use points info icon popup issue

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/airindia#64]
Use points info icon popup is displayed to the right, which brings a white space in the page. This white space exists even when the popup Is closed.

![image](https://github.com/hlxsites/airindia/assets/1191451/09965a9e-a30c-4890-bded-a0e60586ebc5)

**Comment by sselvara** [comment]
@sdmcraft this is fixed as part of the PR #55 and works fine in the main brach https://main--airindia--hlxsites.hlx.page/in/en/book/special-offers/global-connectivity.
