### ISSUE TITLE
Page header overlays chat header in mobile view

### ISSUE THREAD

**Issue by dipratap** [hlxsites/airindia#69]
The one with the girl icon is from original air-india site and should be the expected behaviour.

<img width="176" alt="Screenshot 2024-04-03 at 5 13 36 PM" src="https://github.com/hlxsites/airindia/assets/15969249/7a586a47-c963-4da5-a33c-a5cf13f91fb4">
<img width="173" alt="Screenshot 2024-04-03 at 5 13 45 PM" src="https://github.com/hlxsites/airindia/assets/15969249/5db8e118-a4b1-4aba-bf2d-e1c53cc84dd5">
<img width="172" alt="Screenshot 2024-04-03 at 5 14 01 PM" src="https://github.com/hlxsites/airindia/assets/15969249/515ee042-4c81-49c9-a656-50b6e14f302e">

**Comment by sselvara** [comment]
This will be addressed as part of the PR #70

**Comment by sselvara** [comment]
This is fixed.
