### ISSUE TITLE
Join now and sign in links not working correctly

### ISSUE THREAD

**Issue by dipratap** [hlxsites/airindia#72]
The original site navigates to signin and signup pages but not happening on main one.

<img width="817" alt="Screenshot 2024-04-10 at 5 22 34 PM" src="https://github.com/hlxsites/airindia/assets/15969249/2d544e33-d9e3-4245-aaf5-f151134963aa">

<img width="1534" alt="Screenshot 2024-04-10 at 5 24 08 PM" src="https://github.com/hlxsites/airindia/assets/15969249/e7c7b628-8937-4762-a9cf-43a688c11da3">

**Comment by sselvara** [comment]
@dipratap , @sdmcraft this issue will be taken care as part of the issue #79.
