### ISSUE TITLE
In mobile view profile icon and  signin/signup links in hamburger menu are not clickable

### ISSUE THREAD

**Issue by sselvara** [hlxsites/airindia#84]
Header- In mobile view profile icon and  signin/signup links in hamburger menu are not clickable, Hamburger Menu content  is not scrollable.

_Originally posted by @sselvara in https://github.com/hlxsites/airindia/issues/82#issuecomment-2074004486_

**Comment by sdmcraft** [comment]
Also unable to scroll the menu vertically in mobile view.
